version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: inv
      POSTGRES_USER: invuser
      POSTGRES_PASSWORD: invpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      POSTGRES_DB: inv
      POSTGRES_USER: invuser
      POSTGRES_PASSWORD: invpass
      DB_HOST: db
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
volumes:
  db-data:
